name: Multi-platform Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            deps: sudo apt-get update && sudo apt-get install -y libfontconfig1-dev
            artifact_name: bigsryai-linux-x86_64

          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
            deps: sudo apt-get update && sudo apt-get install -y libfontconfig1-dev
            artifact_name: bigsryai-linux-arm64

          # Windows
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            deps: ""
            artifact_name: bigsryai-windows-x86_64.exe

          # macOS
          - target: x86_64-apple-darwin
            os: macos-14-xlarge
            deps: ""
            artifact_name: bigsryai-macos-x86_64

          - target: aarch64-apple-darwin
            os: macos-latest
            deps: ""
            artifact_name: bigsryai-macos-arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install dependencies
        if: matrix.deps != ''
        run: ${{ matrix.deps }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare artifacts
        shell: bash
        run: |
          mkdir -p artifacts/${{ matrix.target }}
          binary_path="target/${{ matrix.target }}/release/bigsryai"
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            binary_path="$binary_path.exe"
          fi
          cp "$binary_path" "artifacts/${{ matrix.target }}/${{ matrix.artifact_name }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.target }}
          path: artifacts/${{ matrix.target }}/
